server:
  port: 9090
  compression:
    enabled: true

spring:
#  mvc:
#    static-path-pattern: /**
#  resources:
#    static-locations: classpath:/static/
  application:
    name: Welfare
  profiles:
    active: prod

es:
  host: 10.7.97.73
  port: 9200
  pwd: zCPY7OlZEJ5224dMqtho