version: "3.3"
# 注意，使用该脚本启动服务，需要先用`deploy_with_docker.sh`构建好启动所需的镜像 `kylin/welfare`
services:
  welfare_1:
    image: kylin/welfare:latest
    volumes:
      - wyf_attachment:/var/attachment
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always
    environment:
      - WELFARE_VAR="echo"
      - ES_PWD=${ES_PWD}
      - ES_HOST="10.7.97.73"
      - ES_PORT="7200"
      - ES_USER="elastic"
      - TZ="Asia/Shanghai"
    networks:
      - wyf
    ports:
      - "8081:9090"
      # -XX:SurvivorRatio=8 -XX:NewRatio=4 -XX:MetaspaceSize=64m -XX:MaxMetaspaceSize=64m -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCDateStamps -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationStoppedTime -XX:+PrintGCApplicationConcurrentTime -Xloggc:/var/attachment/logs/welfare-1.gc.log
    entrypoint: java -server -XX:+UnlockDiagnosticVMOptions -XX:+UnlockExperimentalVMOptions -XX:-OmitStackTraceInFastThrow  -Dfile.encoding=UTF-8 -Djava.security.egd=file:/dev/./urandom -Dnetworkaddress.cache.ttl=10 -Xms${G1_Xms} -Xmx${G1_Xmx} -Xmn${G1_Xmn} -Xss${G1_Xss} -XX:MaxDirectMemorySize=${G1_DirectMemSize} -XX:MetaspaceSize=${G1_MetaSpace} -XX:ReservedCodeCacheSize=${G1_ReservedCodeCacheSize} -XX:+DisableExplicitGC -XX:MaxGCPauseMillis=${G1_MaxGCPauseMillis} -XX:-UseBiasedLocking -XX:GuaranteedSafepointInterval=0 -XX:+UseCountedLoopSafepoints -XX:StartFlightRecording=disk=true,maxsize=4096m,maxage=3d -XX:FlightRecorderOptions=maxchunksize=128m --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.math=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/java.security=ALL-UNNAMED --add-opens java.base/java.text=ALL-UNNAMED --add-opens java.base/java.time=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/jdk.internal.access=ALL-UNNAMED --add-opens java.base/jdk.internal.misc=ALL-UNNAMED  -jar /app/kylin-welfare.jar
volumes:
  wyf_attachment: {}

networks:
  wyf:
    external: true

